---
- name: "Ensure system's FQDN hostname is set"
  become: True
  hostname:
    name: "{{ hosts_hostname.hostname }}.{{ hosts_hostname.domain }}"
  when:
    - "hosts_hostname is defined"
    - "hosts_hostname.hostname is defined"
    - "hosts_hostname.domain is defined"
    - "hosts_set_hostname | default(True)"
    - "set_ansible_fqdn_as_hostname == False"

- name: "Ensure system's hostname is set"
  become: True
  hostname:
    name: "{{ ansible_fqdn }}"
  when:
    - "ansible_fqdn is defined"
    - "set_ansible_fqdn_as_hostname"

- name: Tell me your hostname
  debug:
    msg: "set hostname to {{ ansible_fqdn }}"
  when:
    - "ansible_fqdn is defined"
    - "set_ansible_fqdn_as_hostname"

- name: "Configure /etc/hosts"
  become: True
  template:
    src: "hosts.j2"
    dest: "/etc/hosts"
    backup: "{{ hosts_backup | default(True) }}"
    owner: "root"
    group: "root"
    mode: "0644"
  when: "hosts_hostname is defined or hosts_add_hosts is defined"
